### ISSUE TITLE
stickynotes-applet crashes with SIGSEGV

### ISSUE THREAD

**Issue by 7F11** [linuxmint/sticky#130]
I have upgraded Linux Mint to version 22.

When I try to open stickynotes-applet from the panel it crashes.
Strace shows that it receives SIGSEGV. 
dmesg wrote:

```
[Sat Aug 17 20:30:22 2024] stickynotes-app[11102]: segfault at 968 ip 000074ab77b1c38d sp 00007ffc76ad5660 error 4 in libX11.so.6.4.0[74ab77b15000+90000] likely on CPU 1 (core 1, socket 0)
[Sat Aug 17 20:30:22 2024] Code: 55 49 89 cd 41 54 45 89 cc 53 44 89 c3 48 83 ec 28 48 8b 45 10 48 89 55 b8 48 89 45 b0 64 48 8b 04 25 28 00 00 00 48 89 45 c8 <48> 8b 87 68 09 00 00 48 85 c0 74 02 ff 10 ba 18 00 00 00 be 12 00
[Sat Aug 17 20:30:34 2024] stickynotes-app[11127]: segfault at 968 ip 00007975a7d4638d sp 00007fffc3427400 error 4 in libX11.so.6.4.0[7975a7d3f000+90000] likely on CPU 1 (core 1, socket 0)
[Sat Aug 17 20:30:34 2024] Code: 55 49 89 cd 41 54 45 89 cc 53 44 89 c3 48 83 ec 28 48 8b 45 10 48 89 55 b8 48 89 45 b0 64 48 8b 04 25 28 00 00 00 48 89 45 c8 <48> 8b 87 68 09 00 00 48 85 c0 74 02 ff 10 ba 18 00 00 00 be 12 00

```
Attachments:

- [Output of strace](https://github.com/user-attachments/files/16646252/trace.gz)
- [Mintreport](https://github.com/user-attachments/files/16646277/mintreport.tar.gz)

Gabor

**Comment by erenfro** [comment]
I'm getting apparently the same issue with this. It's mostly repeatable when you're switching between multiple note groups using the applet, specifically.

Running sticky on the terminal and doing this I got this when it crashed:
```
/usr/bin/sticky: line 3: 1488718 Segmentation fault      (core dumped) /usr/lib/sticky/sticky.py $*
```

From Dmesg about it:
```
[45405.888033] sticky.py[1445583]: segfault at 4dd96 ip 00007f9324490cd8 sp 00007ffd9220f128 error 4 in libgobject-2.0.so.0.8000.0[7f9324463000+37000] likely on CPU 1 (core 1, socket 0)
[45405.888050] Code: 8d 15 8c 54 02 00 48 c1 e9 02 4c 8b 0c ca 4d 85 c9 74 07 41 f6 41 16 20 75 36 48 8b 38 48 81 ff fc 03 00 00 76 3c 48 83 e7 fc <f6> 47 16 10 74 05 4d 85 c9 75 4d 31 c0 c3 66 2e 0f 1f 84 00 00 00
[45435.118780] sticky.py[1488718]: segfault at af56 ip 0000744d1dbe6cd8 sp 00007ffdb15f3068 error 4 in libgobject-2.0.so.0.8000.0[744d1dbb9000+37000] likely on CPU 1 (core 1, socket 0)
[45435.118788] Code: 8d 15 8c 54 02 00 48 c1 e9 02 4c 8b 0c ca 4d 85 c9 74 07 41 f6 41 16 20 75 36 48 8b 38 48 81 ff fc 03 00 00 76 3c 48 83 e7 fc <f6> 47 16 10 74 05 4d 85 c9 75 4d 31 c0 c3 66 2e 0f 1f 84 00 00 00
```

**Comment by mfreeman72** [comment]
I'm getting this by simply right-clicking on the notification icon. The terminal error produced is:
`/usr/bin/sticky:` line 3: 10592 Segmentation fault      (core dumped) /usr/lib/sticky/sticky.py $*`

**Comment by 7F11** [comment]
IMHO your cases are different. Python script `/usr/lib/sticky/sticky.py` seems to work at me. It is ELF executable `/usr/lib/mate-applets/stickynotes-applet` that crashes on my host. Snippet from `ltrace -S -f -p 14320` output:
```14320 gdk_x11_window_get_xid(0, 0x5b0b2838cab0, 0x5b0e98e6334c, 7 <unfinished ...>
14326 <... SYS_getegid32 resumed> )              = 0xfffffe00
14325 <... SYS_madvise1 resumed> )               = 0xfffffdfc
14323 <... SYS_madvise1 resumed> )               = 0xfffffdfc
14322 <... SYS_madvise1 resumed> )               = 0xfffffdfc
14321 <... SYS_getegid32 resumed> )              = 0xfffffe00
14326 SYS_getegid32(0x281a3590, 128, 1, 0 <unfinished ...>
14325 SYS_madvise1(0x60000b90, 1, 0xffffffff, 0x282677a0 <unfinished ...>
14323 SYS_madvise1(0x6c000b90, 2, 0xffffffff, 0x28127060 <unfinished ...>
14322 SYS_madvise1(0x2811ac30, 1, 0xffffffff, 0x2811aa60 <unfinished ...>
14321 SYS_getegid32(0x28117e60, 128, 1, 0 <unfinished ...>
14320 SYS_sendmsg(11, 0x7ffcf2742b50, 0x4000, 128) = 124
14320 <... gdk_x11_window_get_xid resumed> )     = 0
14320 XChangeProperty(0, 0, 0, 6 <unfinished ...>
14326 <... SYS_getegid32 resumed> )              = 0xfffffe00
14325 <... SYS_madvise1 resumed> )               = 0xfffffdfc
14323 <... SYS_madvise1 resumed> )               = 0xfffffdfc
14322 <... SYS_madvise1 resumed> )               = 0xfffffdfc
14321 <... SYS_getegid32 resumed> )              = 0xfffffe00
14326 SYS_getegid32(0x281a3590, 128, 1, 0 <unfinished ...>
14325 SYS_madvise1(0x60000b90, 1, 0xffffffff, 0x282677a0 <unfinished ...>
14323 SYS_madvise1(0x6c000b90, 2, 0xffffffff, 0x28127060 <unfinished ...>
14322 SYS_madvise1(0x2811ac30, 1, 0xffffffff, 0x2811aa60 <unfinished ...>
14321 SYS_getegid32(0x28117e60, 128, 1, 0 <no return ...>
14320 --- SIGSEGV (Segmentation fault) ---
14326 +++ killed by SIGSEGV +++
14325 +++ killed by SIGSEGV +++
14323 +++ killed by SIGSEGV +++
14321 +++ killed by SIGSEGV +++
14322 +++ killed by SIGSEGV +++
14320 +++ killed by SIGSEGV +++```

**Comment by collinss** [comment]
Fixed in 8013f4c9651b222128c1b3a7311769d4db9dc6a0

**Comment by 7F11** [comment]
I refreshed `/usr/lib/sticky/sticky.py` but `/usr/lib/mate-applets/stickynotes-applet` still crashes.
