### ISSUE TITLE
1 pixel bug: There is 1 white pixel on top of my desktop background when StickyNotes are opened

### ISSUE THREAD

**Issue by SebastJava** [linuxmint/sticky#26]
```
● Notes version: 1.1
● Distribution: Linux Mint Cinnamon 20.2
● Screen resolution: FHD = 1920 X 1080
```
![StickyNotes-1-pixel-bug](https://user-images.githubusercontent.com/31940713/125844026-baadf268-29a0-4656-8a17-eff6e8b4f577.png)
_Click to enlarge_

**Issue**
When StickyNotes are opened, there is 1 white pixel on top of my desktop background picture. This white pixel is located exactly at the center of my FHD screen. Please see my screenshot. This 1 pixel bug occurs on any picture, including solid colour backgrounds (Backgrounds > Settings > Picture aspect: No picture...)

**Steps to reproduce**
1. Close or minimize all opened windows so that you can see the center of your background picture.
2. Open StickyNotes. You may need to click on [+] to create a new note. Or just click on the system tray icon.

**Expected behaviour**
I would expect my background image to stay perfect, unchanged.

**Other information**
It took me a while to find where this 1 pixel bug was coming from. I am almost sure it is new to Mint 20.2. And it seems to be coming from StickyNotes, because it appears when i open it and it disappears when i right-click the system tray icon to quit.

**Comment by collinss** [comment]
This is already fixed in master https://github.com/linuxmint/sticky/commit/a3f97680db369a6894b63f74acaeef552b25c091

**Comment by SebastJava** [comment]
@collinss 
I took a quick look at this https://github.com/linuxmint/sticky/commit/a3f97680db369a6894b63f74acaeef552b25c091 and i am not sure we are talking about the same thing. That is probably just because i did not understand much about this commit.

Short story: there is one buggy white pixel on top of my background picture **at the center of the screen.** Please check my zoomed screenshot here.

![StickyNotes-1-pixel-bug-zoom](https://user-images.githubusercontent.com/31940713/125855558-50d185a4-7da7-47b5-af80-2cd20fa78533.png)

So, you are saying this got fixed? Thanks.

**Comment by mtwebster** [comment]
Yes he's saying that.

**Comment by li20034** [comment]
I still have this issue after building a deb package from the git repository and installing that

**Comment by collinss** [comment]
@li20034 This may be a dumb question, but did you make sure to completely quit the app after installing?

**Comment by li20034** [comment]
Yeah, just to be sure, I logged out and back in, but to no avail. I'm using Linux Mint XFCE 20.2 with a screen resolution of 1366x768 (in case this info is useful).

**Comment by collinss** [comment]
Oh, I haven't tested it in xfce. I wonder if xfce is ignoring the request to move the window off-screen or some other wierdness.

**Comment by clefebvre** [comment]
Fixed in 1.2 and 1.2.1

**Comment by preeset** [comment]
This problem still exists in Linux Mint 20.3 - Notes version 1.8. Can someone please suggest a way to get rid of the pixel? It still persists when the program is closed/killed.

**Comment by preeset** [comment]
I just looked at /usr/lib/sticky/sticky.py and it contains this code fix:

https://github.com/linuxmint/sticky/commit/a3f97680db369a6894b63f74acaeef552b25c091

The problem still exists.
